plugins { 
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.tajmul.gapcalculator'
    compileSdk 36
    
    defaultConfig { 
        applicationId "com.tajmul.gapcalculator"
        minSdk 24
        targetSdk 36
        versionCode 12
        versionName "2.2" 
    }
    
    buildTypes { 
        release { minifyEnabled false }
        debug { minifyEnabled false } 
    }
    
    compileOptions { 
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17 
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'com.google.android.gms:play-services-ads:24.6.0'
    implementation 'com.google.android.play:app-update:2.1.0'
    
    // Firebase connection
    implementation platform('com.google.firebase:firebase-bom:34.18.0')
    implementation 'com.google.firebase:firebase-analytics'
}
